version: 2
jobs:
  build:
    docker:
      - image: node:10

    environment:
      NODE_ENV: test

    working_directory: /home/ubuntu/workspace

    parallelism: 1

    steps:
      - checkout

      - restore_cache:
          name: Restore Cache for Packages
          keys:
            - npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-{{ .Branch }}-

      - run: yarn install
      - run: npm run prepare
      - run: npm run test

      - save_cache:
          name: Save Cache for Packages
          key: npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - /home/ubuntu/workspace/node_modules
